version: '3'
services:
  app:
    container_name: app
    restart: always
    build: ../../../
    volumes:
      - ../../../data/logs:/home/bot/app/logs
      - ../../../data/shr:/tmp/shr
    ports:
      - 5005:5005
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - url2api
      - mtproto
      - botapi
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5431:5432
    env_file:
      - .db.env
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command:
      - 'redis-server'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
    volumes:
      - ../../../data/redis:/data
  url2api:
    container_name: url2api
    restart: always
    build: ../../../../url-to-pdf-api/
  mtproto:
    container_name: mtproto
    restart: always
    build: ../../../../fileutils-rest/
    env_file:
      - ../../../../fileutils-rest/.env
    volumes:
      - ../../../data/gram:/home/bot/app/gram
      - ../../../data/shr:/tmp/shr
    depends_on:
      - botapi
  bot:
    container_name: bot
    restart: always
    build: ../../../../fileutils-bot/
    env_file:
      - ../../../../fileutils-bot/.env
    volumes:
      - ../../../data/gram:/home/bot/app/gram
    depends_on:
      - app
  botapi:
    container_name: botapi
    restart: always
    build: ../../../../fileutils-bot-api/
    env_file:
      - ../../../../fileutils-bot-api/.env
    volumes:
      - ../../../data/logs:/app/logs
      - ../../../data/shr:/tmp/shr
volumes:
  pgdata:
    external: true
