version: '3'
services:
  renamerapp:
    container_name: renamerapp
    restart: always
    build: ../../../
    volumes:
      - ../../../data/logs:/home/bot/app/logs
      - ../../../data/shr:/tmp/shr
    ports:
      - 5005:5005
    env_file:
      - .env
    depends_on:
      - renamermtproto
      - renamerbotapi
  renamermtproto:
    container_name: renamermtproto
    restart: always
    build: ../../../../fileutils-rest/
    env_file:
      - .env
    volumes:
      - ../../../data/gram:/home/bot/app/gram
      - ../../../data/shr:/tmp/shr
    depends_on:
      - renamerbotapi
  renamerbot:
    container_name: renamerbot
    restart: always
    build: ../../../../fileutils-bot/
    env_file:
      - .env
    volumes:
      - ../../../data/gram:/home/bot/app/gram
    depends_on:
      - renamerapp
  renamerbotapi:
    container_name: renamerbotapi
    restart: always
    build: ../../../../fileutils-bot-api/
    env_file:
      - .env
    volumes:
      - ../../../data/logs:/app/logs
      - ../../../data/shr:/tmp/shr
volumes:
  pgdata:
    external: true
